Safir SDK Core: Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT > Class Template Reference
Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT > Class Template Reference
Container class for dictionaries of key value pairs.
#include <Safir/Dob/Typesystem/DictionaryContainer.h>
Public Types
typedef KeyT KeyType
typedef ValT ValueContainerType
typedef ValueContainerType::ContainedType ContainedType
typedef std::map< KeyType, ValueContainerType > StorageType
typedef StorageType::const_iterator const_iterator
typedef StorageType::iterator iterator
typedef StorageType::value_type value_type
Public Member Functions
DictionaryContainer ()
Default Constructor.
virtual bool IsNull () const
Is the container set to null?
virtual void SetNull ()
Set the container to null.
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
iterator find (const KeyType &key)
const_iterator find (const KeyType &key) const
size_t size () const
bool empty () const
size_t count (const KeyType &key) const
ValueContainerType & operator[] (const KeyType &key)
virtual bool IsChanged () const
IsChanged - Check if the sequence has changed.
virtual void SetChanged (const bool changed)
SetChanged - Set the change state of the sequence.
void clear ()
clear - Clear the sequence, i.e remove all values.
void Insert (const KeyType &key, const ContainedType &val)
size_t erase (const KeyType &key)
virtual void Copy (const ContainerBase &that)
Copy - Copy all the members from "that" into "this".
Public Member Functions inherited from Safir::Dob::Typesystem::ContainerBase
ContainerBase ()
Default Constructor.
virtual ~ContainerBase ()
Virtual destructor.
Additional Inherited Members
Protected Member Functions inherited from Safir::Dob::Typesystem::ContainerBase
ContainerBase & operator= (const ContainerBase &other)
Copy assignment operator.
Protected Attributes inherited from Safir::Dob::Typesystem::ContainerBase
bool m_bIsChanged
The variable containing the change flag.
Detailed Description
template<class KeyT, class ValT>
class Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >
Container class for dictionaries of key value pairs.
A dictionary is a collection of values that can dynamically grow or shrink in size. The whole container has a change flag that will automatically be set when values are added, removed or changed.
Member Typedef Documentation
template<class KeyT, class ValT> typedef StorageType::const_iterator Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::const_iterator
template<class KeyT, class ValT> typedef ValueContainerType::ContainedType Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::ContainedType
template<class KeyT, class ValT> typedef StorageType::iterator Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::iterator
template<class KeyT, class ValT> typedef KeyT Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::KeyType
template<class KeyT, class ValT> typedef std::map<KeyType, ValueContainerType> Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::StorageType
template<class KeyT, class ValT> typedef StorageType::value_type Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::value_type
template<class KeyT, class ValT> typedef ValT Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::ValueContainerType
Constructor & Destructor Documentation
template<class KeyT, class ValT> Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::DictionaryContainer ()
Default Constructor.
Construct a container that is not changed and not null.
Member Function Documentation
template<class KeyT, class ValT> iterator Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::begin ()
Referenced by Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::Copy().
template<class KeyT, class ValT> const_iterator Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::begin () const
template<class KeyT, class ValT> void Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::clear ()
clear - Clear the sequence, i.e remove all values.
After a call to clear the sequence will be empty but not automatically set to null.
References Safir::Dob::Typesystem::ContainerBase::m_bIsChanged.
Referenced by Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::Copy().
template<class KeyT, class ValT> virtual void Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::Copy (const ContainerBase & that) virtual
Copy - Copy all the members from "that" into "this".
Types must be the same for this to work!
Parameters
that [in] - The object to copy into this.
Exceptions
SoftwareViolationException If the types are not of the same kind.
Implements Safir::Dob::Typesystem::ContainerBase.
References __WFILE__, Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::begin(), Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::clear(), Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::end(), and Safir::Dob::Typesystem::ContainerBase::m_bIsChanged.
template<class KeyT, class ValT> size_t Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::count (const KeyType & key) const
Referenced by Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::erase().
template<class KeyT, class ValT> bool Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::empty () const
template<class KeyT, class ValT> iterator Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::end ()
Referenced by Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::Copy().
template<class KeyT, class ValT> const_iterator Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::end () const
template<class KeyT, class ValT> size_t Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::erase (const KeyType & key)
References Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::count(), and Safir::Dob::Typesystem::ContainerBase::m_bIsChanged.
template<class KeyT, class ValT> iterator Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::find (const KeyType & key)
template<class KeyT, class ValT> const_iterator Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::find (const KeyType & key) const
template<class KeyT, class ValT> void Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::Insert (const KeyType & key, const ContainedType & val)
References Safir::Dob::Typesystem::ContainerBase::m_bIsChanged.
template<class KeyT, class ValT> virtual bool Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::IsChanged () const virtual
IsChanged - Check if the sequence has changed.
Returns
True if changed, else false.
Reimplemented from Safir::Dob::Typesystem::ContainerBase.
References Safir::Dob::Typesystem::ContainerBase::m_bIsChanged.
template<class KeyT, class ValT> virtual bool Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::IsNull () const virtual
Is the container set to null?
Returns
True if the container is set to null.
Implements Safir::Dob::Typesystem::ContainerBase.
template<class KeyT, class ValT> ValueContainerType& Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::operator[] (const KeyType & key)
References Safir::Dob::Typesystem::ContainerBase::m_bIsChanged.
template<class KeyT, class ValT> virtual void Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::SetChanged (const bool changed) virtual
SetChanged - Set the change state of the sequence.
Parameters
changed [in] - If true, the sequence is set to changed, it is set to not changed.
Reimplemented from Safir::Dob::Typesystem::ContainerBase.
References Safir::Dob::Typesystem::ContainerBase::m_bIsChanged.
template<class KeyT, class ValT> virtual void Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::SetNull () virtual
Set the container to null.
Implements Safir::Dob::Typesystem::ContainerBase.
References __WFILE__.
template<class KeyT, class ValT> size_t Safir::Dob::Typesystem::DictionaryContainer< KeyT, ValT >::size () const