Safir SDK Core: Safir::Dob::Typesystem::ContainerProxy< T > Class Template Reference
Safir::Dob::Typesystem::ContainerProxy< T > Class Template Reference
#include <Safir/Dob/Typesystem/ContainerProxies.h>
Public Types
typedef T::ContainedType ContainedType
Public Member Functions
ContainerProxy (T &container)
ContainerProxy & operator= (const ContainerProxy &other)
ContainerProxy & operator= (const ContainedType other)
operator const ContainedType () const
bool IsNull () const
void SetNull ()
bool IsChanged () const
void SetChanged (const bool changed)
void SetVal (const ContainedType value)
const ContainedType GetVal () const
void SetOrdinal (const EnumerationValue value)
EnumerationValue GetOrdinal () const
void Copy (const ContainerProxy &that)
ContainerProxy & operator++ ()
void operator++ (int)
ContainerProxy & operator-- ()
void operator-- (int)
ContainerProxy & operator+= (const ContainedType &val)
ContainerProxy & operator-= (const ContainedType &val)
ContainerProxy & operator*= (const ContainedType &val)
ContainerProxy & operator/= (const ContainedType &val)
const T & GetContainer () const
T & GetContainer ()
Member Typedef Documentation
template<class T> typedef T::ContainedType Safir::Dob::Typesystem::ContainerProxy< T >::ContainedType
Constructor & Destructor Documentation
template<class T> Safir::Dob::Typesystem::ContainerProxy< T >::ContainerProxy (T & container) explicit
Member Function Documentation
template<class T> void Safir::Dob::Typesystem::ContainerProxy< T >::Copy (const ContainerProxy< T > & that)
template<class T> const T& Safir::Dob::Typesystem::ContainerProxy< T >::GetContainer () const
template<class T> T& Safir::Dob::Typesystem::ContainerProxy< T >::GetContainer ()
template<class T> EnumerationValue Safir::Dob::Typesystem::ContainerProxy< T >::GetOrdinal () const
template<class T> const ContainedType Safir::Dob::Typesystem::ContainerProxy< T >::GetVal () const
Referenced by Safir::Dob::Typesystem::ContainerProxy< T >::operator*=(), Safir::Dob::Typesystem::ContainerProxy< T >::operator++(), Safir::Dob::Typesystem::ContainerProxy< T >::operator+=(), Safir::Dob::Typesystem::ContainerProxy< StringContainer >::operator+=(), Safir::Dob::Typesystem::ContainerProxy< T >::operator--(), Safir::Dob::Typesystem::ContainerProxy< T >::operator-=(), Safir::Dob::Typesystem::ContainerProxy< T >::operator/=(), Safir::Dob::Typesystem::ContainerProxy< T >::operator=(), Safir::Dob::Typesystem::ContainerProxy< StringContainer >::operator=(), and Safir::Dob::Typesystem::ContainerProxy< BinaryContainer >::operator=().
template<class T> bool Safir::Dob::Typesystem::ContainerProxy< T >::IsChanged () const
template<class T> bool Safir::Dob::Typesystem::ContainerProxy< T >::IsNull () const
Referenced by Safir::Dob::Typesystem::ContainerProxy< T >::operator=(), Safir::Dob::Typesystem::ContainerProxy< StringContainer >::operator=(), Safir::Dob::Typesystem::ContainerProxy< BinaryContainer >::operator=(), Safir::Dob::Typesystem::ContainerProxy< ObjectContainerImpl< U > >::operator=(), and Safir::Dob::Typesystem::ContainerProxy< ObjectContainerImpl< Object > >::operator=().
template<class T> Safir::Dob::Typesystem::ContainerProxy< T >::operator const ContainedType () const
template<class T> ContainerProxy& Safir::Dob::Typesystem::ContainerProxy< T >::operator*= (const ContainedType & val)
References Safir::Dob::Typesystem::ContainerProxy< T >::GetVal(), and Safir::Dob::Typesystem::ContainerProxy< T >::SetVal().
template<class T> ContainerProxy& Safir::Dob::Typesystem::ContainerProxy< T >::operator++ ()
References Safir::Dob::Typesystem::ContainerProxy< T >::GetVal(), and Safir::Dob::Typesystem::ContainerProxy< T >::SetVal().
template<class T> void Safir::Dob::Typesystem::ContainerProxy< T >::operator++ (int)
template<class T> ContainerProxy& Safir::Dob::Typesystem::ContainerProxy< T >::operator+= (const ContainedType & val)
References Safir::Dob::Typesystem::ContainerProxy< T >::GetVal(), and Safir::Dob::Typesystem::ContainerProxy< T >::SetVal().
template<class T> ContainerProxy& Safir::Dob::Typesystem::ContainerProxy< T >::operator-- ()
References Safir::Dob::Typesystem::ContainerProxy< T >::GetVal(), and Safir::Dob::Typesystem::ContainerProxy< T >::SetVal().
template<class T> void Safir::Dob::Typesystem::ContainerProxy< T >::operator-- (int)
template<class T> ContainerProxy& Safir::Dob::Typesystem::ContainerProxy< T >::operator-= (const ContainedType & val)
References Safir::Dob::Typesystem::ContainerProxy< T >::GetVal(), and Safir::Dob::Typesystem::ContainerProxy< T >::SetVal().
template<class T> ContainerProxy& Safir::Dob::Typesystem::ContainerProxy< T >::operator/= (const ContainedType & val)
References Safir::Dob::Typesystem::ContainerProxy< T >::GetVal(), and Safir::Dob::Typesystem::ContainerProxy< T >::SetVal().
template<class T> ContainerProxy& Safir::Dob::Typesystem::ContainerProxy< T >::operator= (const ContainerProxy< T > & other)
References Safir::Dob::Typesystem::ContainerProxy< T >::GetVal(), and Safir::Dob::Typesystem::ContainerProxy< T >::IsNull().
template<class T> ContainerProxy& Safir::Dob::Typesystem::ContainerProxy< T >::operator= (const ContainedType other)
template<class T> void Safir::Dob::Typesystem::ContainerProxy< T >::SetChanged (const bool changed)
template<class T> void Safir::Dob::Typesystem::ContainerProxy< T >::SetNull ()
template<class T> void Safir::Dob::Typesystem::ContainerProxy< T >::SetOrdinal (const EnumerationValue value)
template<class T> void Safir::Dob::Typesystem::ContainerProxy< T >::SetVal (const ContainedType value)
Referenced by Safir::Dob::Typesystem::ContainerProxy< T >::operator*=(), Safir::Dob::Typesystem::ContainerProxy< T >::operator++(), Safir::Dob::Typesystem::ContainerProxy< T >::operator+=(), Safir::Dob::Typesystem::ContainerProxy< StringContainer >::operator+=(), Safir::Dob::Typesystem::ContainerProxy< T >::operator--(), Safir::Dob::Typesystem::ContainerProxy< T >::operator-=(), and Safir::Dob::Typesystem::ContainerProxy< T >::operator/=().