Safir SDK Core: Safir::Dob::Typesystem::ObjectContainerImpl< Object > Class Template Reference
Safir::Dob::Typesystem::ObjectContainerImpl< Object > Class Template Reference
This is a specialization of the ObjectContainerImpl template for the case where the template argument is Dob::Typesystem::Object.
#include <Safir/Dob/Typesystem/ObjectContainer.h>
Public Types
typedef boost::shared_ptr< Object > T_Ptr
Typedef for the contained smart pointer.
typedef T_Ptr ContainedType
Public Member Functions
ObjectContainerImpl ()
Default constructor.
ObjectContainerImpl (const ObjectContainerImpl &other)
Copy constructor.
ObjectContainerImpl & operator= (const ObjectContainerImpl &other)
Copy assignment operator.
virtual void SetPtr (const ObjectPtr &ptr)
Set the smart pointer in the container.
const T_Ptr & GetPtr () const
Get the smart pointer from the container.
Object *const operator-> () const
Dereference the smart pointer in the container.
virtual void SetChanged (const bool changed)
Set the containers change flag.
virtual bool IsChanged () const
Is the change flag set on the container? The change flag gets updated every time the contained value changes.
virtual bool IsNull () const
Is the container set to null?
virtual void SetNull ()
Set the container to null.
virtual void Copy (const ContainerBase &that)
Virtual assignment.
virtual ContainerBase & GetMember (const int member, const int index)
Get a reference to a member container from an object.
virtual const ContainerBase & GetMember (const int member, const int index) const
Get a const reference to a member container from an object.
Public Member Functions inherited from Safir::Dob::Typesystem::ObjectContainerBase
ObjectContainerBase ()
Default constructor.
bool IsChangedHere () const
Is the change flag in the container set?
void SetChangedHere (const bool changed)
Set the change flag in the container.
Public Member Functions inherited from Safir::Dob::Typesystem::ContainerBase
ContainerBase ()
Default Constructor.
virtual ~ContainerBase ()
Virtual destructor.
Additional Inherited Members
Protected Member Functions inherited from Safir::Dob::Typesystem::ObjectContainerBase
ObjectContainerBase & operator= (const ObjectContainerBase &other)
Copy assignment operator.
Protected Member Functions inherited from Safir::Dob::Typesystem::ContainerBase
ContainerBase & operator= (const ContainerBase &other)
Copy assignment operator.
Protected Attributes inherited from Safir::Dob::Typesystem::ContainerBase
bool m_bIsChanged
The variable containing the change flag.
Detailed Description
template<>
class Safir::Dob::Typesystem::ObjectContainerImpl< Object >
This is a specialization of the ObjectContainerImpl template for the case where the template argument is Dob::Typesystem::Object.
The reason that this is needed is that for example the SetPtr function will be multiply defined if the ObjectContainerImpl is instantiated with Object.
Member Typedef Documentation
typedef T_Ptr Safir::Dob::Typesystem::ObjectContainerImpl< Object >::ContainedType
typedef boost::shared_ptr<Object> Safir::Dob::Typesystem::ObjectContainerImpl< Object >::T_Ptr
Typedef for the contained smart pointer.
Constructor & Destructor Documentation
Safir::Dob::Typesystem::ObjectContainerImpl< Object >::ObjectContainerImpl ()
Default constructor.
Creates a null and not changed container.
Safir::Dob::Typesystem::ObjectContainerImpl< Object >::ObjectContainerImpl (const ObjectContainerImpl< Object > & other)
Copy constructor.
Copy an object container. The contained object will be cloned.
Parameters
other [in] - The object to copy.
References Safir::Dob::Typesystem::ObjectContainerImpl< T >::IsNull().
Member Function Documentation
virtual void Safir::Dob::Typesystem::ObjectContainerImpl< Object >::Copy (const ContainerBase & that) virtual
Virtual assignment.
Copy all the members from "that" into "this". Types must be the same for this to work!
Parameters
that [in] - The object to copy into this.
Exceptions
SoftwareViolationException If the types are not of the same kind.
Implements Safir::Dob::Typesystem::ContainerBase.
References __WFILE__, Safir::Dob::Typesystem::ContainerBase::IsNull(), Safir::Dob::Typesystem::ContainerBase::m_bIsChanged, and Safir::Dob::Typesystem::ObjectContainerImpl< T >::SetObjectPointer().
virtual ContainerBase& Safir::Dob::Typesystem::ObjectContainerImpl< Object >::GetMember (const int member, const int index) virtual
Get a reference to a member container from an object.
Use the methods in Members to get member indices and array sizes for use with this method.
Note: Do not use this method unless you're very sure it is the one you need!
Parameters
member [in] - The index of the member to get.
index [in] - The array index of the member to get.
Returns
A reference to the member container.
Exceptions
IllegalValueException If the index is not in the range of the array.
SoftwareViolationException If the element is not an array and the index is not 0.
Implements Safir::Dob::Typesystem::ObjectContainerBase.
References __WFILE__, and Safir::Dob::Typesystem::ObjectContainerImpl< T >::IsNull().
virtual const ContainerBase& Safir::Dob::Typesystem::ObjectContainerImpl< Object >::GetMember (const int member, const int index) const virtual
Get a const reference to a member container from an object.
Use the methods in Members to get member indices and array sizes for use with this method.
Note: Do not use this method unless you're very sure it is the one you need!
Parameters
member [in] - The index of the member to get.
index [in] - The array index of the member to get.
Returns
A const reference to the member container.
Exceptions
IllegalValueException If the index is not in the range of the array.
SoftwareViolationException If the element is not an array and the index is not 0.
Implements Safir::Dob::Typesystem::ObjectContainerBase.
References __WFILE__, and Safir::Dob::Typesystem::ObjectContainerImpl< T >::IsNull().
const T_Ptr& Safir::Dob::Typesystem::ObjectContainerImpl< Object >::GetPtr () const
Get the smart pointer from the container.
This method will return the contained smart pointer unless the container is null, then an exception will be thrown.
Returns
A smart pointer to the contained object.
Exceptions
NullException The container is null.
References __WFILE__, and Safir::Dob::Typesystem::ObjectContainerImpl< T >::IsNull().
virtual bool Safir::Dob::Typesystem::ObjectContainerImpl< Object >::IsChanged () const virtual
Is the change flag set on the container? The change flag gets updated every time the contained value changes.
Note: If this is a container containing an object this call will recursively check change flags in the contained object.
Returns
True if the containers change flag is set.
Reimplemented from Safir::Dob::Typesystem::ContainerBase.
References Safir::Dob::Typesystem::ObjectContainerImpl< T >::IsNull(), and Safir::Dob::Typesystem::ContainerBase::m_bIsChanged.
virtual bool Safir::Dob::Typesystem::ObjectContainerImpl< Object >::IsNull () const virtual
Is the container set to null?
Returns
True if the container is set to null.
Implements Safir::Dob::Typesystem::ContainerBase.
Object* const Safir::Dob::Typesystem::ObjectContainerImpl< Object >::operator-> () const
Dereference the smart pointer in the container.
This method will call the -> operator on the smart pointer in the container to allow users to directly access members in the object.
Returns
A pointer to the contained object.
Exceptions
NullException The container is null.
References __WFILE__, and Safir::Dob::Typesystem::ObjectContainerImpl< T >::IsNull().
ObjectContainerImpl& Safir::Dob::Typesystem::ObjectContainerImpl< Object >::operator= (const ObjectContainerImpl< Object > & other)
Copy assignment operator.
Parameters
other [in] - The object to copy.
Returns
A reference to this.
References Safir::Dob::Typesystem::ObjectContainerImpl< T >::IsNull(), and Safir::Dob::Typesystem::ObjectContainerBase::operator=().
virtual void Safir::Dob::Typesystem::ObjectContainerImpl< Object >::SetChanged (const bool changed) virtual
Set the containers change flag.
It should be fairly unusual for an application to have to use this operation. There is nothing dangerous about it, but are you sure this is the operation you were after?
The change flag is how receivers of objects can work out what the sender really wanted done on the object.
Note: If this is a container containing an object this call will recursively set all the change flags in the contained object.
Parameters
changed [in] - The value to set the change flag(s) to.
Reimplemented from Safir::Dob::Typesystem::ContainerBase.
References Safir::Dob::Typesystem::ObjectContainerImpl< T >::IsNull(), and Safir::Dob::Typesystem::ContainerBase::m_bIsChanged.
virtual void Safir::Dob::Typesystem::ObjectContainerImpl< Object >::SetNull () virtual
Set the container to null.
Implements Safir::Dob::Typesystem::ContainerBase.
References Safir::Dob::Typesystem::ContainerBase::m_bIsChanged.
virtual void Safir::Dob::Typesystem::ObjectContainerImpl< Object >::SetPtr (const ObjectPtr & ptr) virtual
Set the smart pointer in the container.
This method will set the contained pointer to point to another object. Checks are always made to see that it is of the correct type. The change flag of the container will be updated.
Parameters
ptr [in] A pointer to the new object to point to.
Exceptions
IncompatibleTypesException If the ptr is not of the type contained by the container.
Implements Safir::Dob::Typesystem::ObjectContainerBase.
References Safir::Dob::Typesystem::ContainerBase::m_bIsChanged.