Safir SDK Core: Safir::Dob::Typesystem::ObjectContainerImpl< T > Class Template Reference
Safir::Dob::Typesystem::ObjectContainerImpl< T > Class Template Reference
Template class for all containers of automatically generated DOB objects.
#include <Safir/Dob/Typesystem/ObjectContainer.h>
Public Types
typedef std::shared_ptr< T > T_Ptr
Typedef for the contained smart pointer.
typedef T_Ptr ContainedType
Public Member Functions
ObjectContainerImpl ()
Default constructor.
ObjectContainerImpl (const ObjectContainerImpl &other)
Copy constructor.
ObjectContainerImpl & operator= (const ObjectContainerImpl &other)
Copy assignment operator.
void SetPtr (const T_Ptr &ptr)
Set the smart pointer in the container.
void SetPtr (const ObjectPtr &ptr) override
Set the smart pointer in the container.
const T_Ptr & GetPtr () const
Get the smart pointer from the container.
T * operator-> () const
Dereference the smart pointer in the container.
void SetChanged (const bool changed) override
Set the containers change flag.
bool IsChanged () const override
Is the change flag set on the container?
bool IsNull () const override
Is the container set to null?
void SetNull () override
Set the container to null.
void Copy (const ContainerBase &that) override
Virtual assignment.
ContainerBase & GetMember (const int member, const int index) override
Get a reference to a member container from an object.
const ContainerBase & GetMember (const int member, const int index) const override
Get a const reference to a member container from an object.
const ObjectPtr GetObjectPointer () const override
Get a smart pointer to the contained object.
void SetObjectPointer (const ObjectPtr ptr) override
Set the smart pointer in the container.
void ResetObjectPointer () override
Reset (ie set to null) the contained pointer.
Blob serialization/deserialization part.
These functions are for internal use only! Their names and functionality are likely to change in the near future!
Int32 CalculateBlobSize () const
Calculate the size of the blob-serialized form of the contained object.
Public Member Functions inherited from Safir::Dob::Typesystem::ObjectContainerBase
ObjectContainerBase ()
Default constructor.
ObjectContainerBase (const ObjectContainerBase &)=default
Copy constructor.
virtual void SetPtr (const ObjectPtr &ptr)=0
Set the smart pointer in the container.
bool IsChangedHere () const
Is the change flag in the container set?
void SetChangedHere (const bool changed)
Set the change flag in the container.
Public Member Functions inherited from Safir::Dob::Typesystem::ContainerBase
constexpr ContainerBase ()
Default Constructor.
constexpr ContainerBase (const ContainerBase &)=default
Copy constructor.
virtual ~ContainerBase ()
Virtual destructor.
virtual bool IsNull () const =0
Is the container set to null?
virtual void SetNull ()=0
Set the container to null.
virtual bool IsChanged () const
Is the change flag set on the container?
virtual void SetChanged (const bool changed)
Set the containers change flag.
virtual void Copy (const ContainerBase &that)=0
Virtual assignment.
Additional Inherited Members
Protected Member Functions inherited from Safir::Dob::Typesystem::ObjectContainerBase
ObjectContainerBase & operator= (const ObjectContainerBase &other)
Copy assignment operator.
Protected Member Functions inherited from Safir::Dob::Typesystem::ContainerBase
ContainerBase & operator= (const ContainerBase &other)
Copy assignment operator.
Protected Attributes inherited from Safir::Dob::Typesystem::ContainerBase
bool m_bIsChanged
The variable containing the change flag.
Detailed Description
template<class T>
class Safir::Dob::Typesystem::ObjectContainerImpl< T >
Template class for all containers of automatically generated DOB objects.
This class holds a smart pointer to an object, and has operations to get information from it and modify it. The -> operator is overloaded to make this class more transparent to use.
It is called ObjectContainerImpl because the name ObjectContainer is "taken" by the container that contains a Dob::Typesystem::Object object.
Parameters
T The type to contain. Must inherit from Dob::Typesystem::Object.
Member Typedef Documentation
ContainedType
template<class T > typedef T_Ptr Safir::Dob::Typesystem::ObjectContainerImpl< T >::ContainedType
T_Ptr
template<class T > typedef std::shared_ptr<T> Safir::Dob::Typesystem::ObjectContainerImpl< T >::T_Ptr
Typedef for the contained smart pointer.
Constructor & Destructor Documentation
ObjectContainerImpl() [1/2]
template<class T > Safir::Dob::Typesystem::ObjectContainerImpl< T >::ObjectContainerImpl ()
Default constructor.
Creates a null and not changed container.
ObjectContainerImpl() [2/2]
template<class T > Safir::Dob::Typesystem::ObjectContainerImpl< T >::ObjectContainerImpl (const ObjectContainerImpl< T > & other)
Copy constructor.
Copy an object container. The contained object will be cloned.
Parameters
other [in] - The object to copy.
Exceptions
IncompatibleTypesException Something has gone horribly wrong with your copying!
References __WFILE__, and Safir::Dob::Typesystem::ObjectContainerImpl< T >::IsNull().
Member Function Documentation
CalculateBlobSize()
template<class T > Int32 Safir::Dob::Typesystem::ObjectContainerImpl< T >::CalculateBlobSize () const
Calculate the size of the blob-serialized form of the contained object.
Returns
The needed size in bytes. 0 if the container is null.
References Safir::Dob::Typesystem::ObjectContainerImpl< T >::IsNull().
Copy()
template<class T > void Safir::Dob::Typesystem::ObjectContainerImpl< T >::Copy (const ContainerBase & that) override virtual
Virtual assignment.
Copy all the members from "that" into "this". Types must be the same for this to work!
Parameters
that [in] - The object to copy into this.
Exceptions
SoftwareViolationException If the types are not of the same kind.
Implements Safir::Dob::Typesystem::ContainerBase.
References __WFILE__, Safir::Dob::Typesystem::ContainerBase::IsNull(), Safir::Dob::Typesystem::ContainerBase::m_bIsChanged, and Safir::Dob::Typesystem::ObjectContainerImpl< T >::SetObjectPointer().
GetMember() [1/2]
template<class T > const ContainerBase & Safir::Dob::Typesystem::ObjectContainerImpl< T >::GetMember (const int member, const int index) const override virtual
Get a const reference to a member container from an object.
Use the methods in Members to get member indices and array sizes for use with this method.
Note: Do not use this method unless you're very sure it is the one you need!
Parameters
member [in] - The index of the member to get.
index [in] - The array index of the member to get.
Returns
A const reference to the member container.
Exceptions
IllegalValueException If the index is not in the range of the array.
SoftwareViolationException If the element is not an array and the index is not 0.
Implements Safir::Dob::Typesystem::ObjectContainerBase.
References __WFILE__, and Safir::Dob::Typesystem::ObjectContainerImpl< T >::IsNull().
GetMember() [2/2]
template<class T > ContainerBase & Safir::Dob::Typesystem::ObjectContainerImpl< T >::GetMember (const int member, const int index) override virtual
Get a reference to a member container from an object.
Use the methods in Members to get member indices and array sizes for use with this method.
Note: Do not use this method unless you're very sure it is the one you need!
Parameters
member [in] - The index of the member to get.
index [in] - The array index of the member to get.
Returns
A reference to the member container.
Exceptions
IllegalValueException If the index is not in the range of the array.
SoftwareViolationException If the element is not an array and the index is not 0.
Implements Safir::Dob::Typesystem::ObjectContainerBase.
References __WFILE__, and Safir::Dob::Typesystem::ObjectContainerImpl< T >::IsNull().
GetObjectPointer()
template<class T > const ObjectPtr Safir::Dob::Typesystem::ObjectContainerImpl< T >::GetObjectPointer () const override virtual
Get a smart pointer to the contained object.
This method will cast the smart object pointer to the derived type contained by the container to a smart pointer to an Object (the DOB object base class.
This method does not check if the container is null!
Note: Do not use this method unless you're very sure it is the one you need!
Returns
A smart pointer to the contained object.
Implements Safir::Dob::Typesystem::ObjectContainerBase.
GetPtr()
template<class T > const T_Ptr & Safir::Dob::Typesystem::ObjectContainerImpl< T >::GetPtr () const
Get the smart pointer from the container.
This method will return the contained smart pointer unless the container is null, then an exception will be thrown.
Returns
A smart pointer to the contained object.
Exceptions
NullException The container is null.
References __WFILE__, and Safir::Dob::Typesystem::ObjectContainerImpl< T >::IsNull().
IsChanged()
template<class T > bool Safir::Dob::Typesystem::ObjectContainerImpl< T >::IsChanged () const override virtual
Is the change flag set on the container?
The change flag gets updated every time the contained value changes.
Note: If this is a container containing objects this call will recursively check change flags in the contained objects.
Returns
True if the containers change flag is set.
Reimplemented from Safir::Dob::Typesystem::ContainerBase.
References Safir::Dob::Typesystem::ObjectContainerImpl< T >::IsNull(), and Safir::Dob::Typesystem::ContainerBase::m_bIsChanged.
IsNull()
template<class T > bool Safir::Dob::Typesystem::ObjectContainerImpl< T >::IsNull () const override virtual
Is the container set to null?
Returns
True if the container is set to null.
Implements Safir::Dob::Typesystem::ContainerBase.
Referenced by Safir::Dob::Typesystem::ObjectContainerImpl< T >::ObjectContainerImpl(), Safir::Dob::Typesystem::ObjectContainerImpl< Object >::ObjectContainerImpl(), Safir::Dob::Typesystem::ObjectContainerImpl< T >::CalculateBlobSize(), Safir::Dob::Typesystem::ObjectContainerImpl< T >::GetMember(), Safir::Dob::Typesystem::ObjectContainerImpl< Object >::GetMember(), Safir::Dob::Typesystem::ObjectContainerImpl< T >::GetPtr(), Safir::Dob::Typesystem::ObjectContainerImpl< Object >::GetPtr(), Safir::Dob::Typesystem::ObjectContainerImpl< T >::IsChanged(), Safir::Dob::Typesystem::ObjectContainerImpl< Object >::IsChanged(), Safir::Dob::Typesystem::ObjectContainerImpl< T >::operator->(), Safir::Dob::Typesystem::ObjectContainerImpl< Object >::operator->(), Safir::Dob::Typesystem::ObjectContainerImpl< T >::operator=(), Safir::Dob::Typesystem::ObjectContainerImpl< Object >::operator=(), Safir::Dob::Typesystem::ObjectContainerImpl< T >::SetChanged(), and Safir::Dob::Typesystem::ObjectContainerImpl< Object >::SetChanged().
operator->()
template<class T > T * Safir::Dob::Typesystem::ObjectContainerImpl< T >::operator-> () const
Dereference the smart pointer in the container.
This method will call the -> operator on the smart pointer in the container to allow users to directly access members in the object.
Returns
A pointer to the contained object.
Exceptions
NullException The container is null.
References __WFILE__, and Safir::Dob::Typesystem::ObjectContainerImpl< T >::IsNull().
operator=()
template<class T > ObjectContainerImpl & Safir::Dob::Typesystem::ObjectContainerImpl< T >::operator= (const ObjectContainerImpl< T > & other)
Copy assignment operator.
Parameters
other [in] - The object to copy.
Returns
A reference to this.
Exceptions
IncompatibleTypesException The contained types are not compatible!
References __WFILE__, Safir::Dob::Typesystem::ObjectContainerImpl< T >::IsNull(), and Safir::Dob::Typesystem::ObjectContainerBase::operator=().
ResetObjectPointer()
template<class T > void Safir::Dob::Typesystem::ObjectContainerImpl< T >::ResetObjectPointer () override virtual
Reset (ie set to null) the contained pointer.
Warning: This method does not update the change flag!
Note: Do not use this method unless you're very sure it is the one you need!
Implements Safir::Dob::Typesystem::ObjectContainerBase.
SetChanged()
template<class T > void Safir::Dob::Typesystem::ObjectContainerImpl< T >::SetChanged (const bool changed) override virtual
Set the containers change flag.
It should be fairly unusual for an application to have to use this operation. There is nothing dangerous about it, but are you sure this is the operation you were after?
The change flag is how receivers of objects can work out what the sender really wanted done on the object.
Note: If this is a container containing one or more objects this call will recursively set all the change flags in the contained objects.
Parameters
changed [in] - The value to set the change flag(s) to.
Reimplemented from Safir::Dob::Typesystem::ContainerBase.
References Safir::Dob::Typesystem::ObjectContainerImpl< T >::IsNull(), and Safir::Dob::Typesystem::ContainerBase::m_bIsChanged.
SetNull()
template<class T > void Safir::Dob::Typesystem::ObjectContainerImpl< T >::SetNull () override virtual
Set the container to null.
Implements Safir::Dob::Typesystem::ContainerBase.
References Safir::Dob::Typesystem::ContainerBase::m_bIsChanged.
SetObjectPointer()
template<class T > void Safir::Dob::Typesystem::ObjectContainerImpl< T >::SetObjectPointer (const ObjectPtr ptr) override virtual
Set the smart pointer in the container.
This method will set the contained pointer to point to another object. Checks are NOT always made to see that it is of the correct type.
Warning: This method does not update the change flag!
Note: Do not use this method unless you're very sure it is the one you need!
Parameters
ptr [in] A pointer to the new object to point to.
Implements Safir::Dob::Typesystem::ObjectContainerBase.
References __WFILE__.
Referenced by Safir::Dob::Typesystem::ObjectContainerImpl< T >::Copy(), and Safir::Dob::Typesystem::ObjectContainerImpl< Object >::Copy().
SetPtr() [1/2]
template<class T > void Safir::Dob::Typesystem::ObjectContainerImpl< T >::SetPtr (const ObjectPtr & ptr) override virtual
Set the smart pointer in the container.
This method will set the contained pointer to point to another object. Checks are always made to see that it is of the correct type. The change flag of the container will be updated.
Parameters
ptr [in] A pointer to the new object to point to.
Exceptions
IncompatibleTypesException If the ptr is not of the type contained by the container.
Implements Safir::Dob::Typesystem::ObjectContainerBase.
References __WFILE__, and Safir::Dob::Typesystem::ContainerBase::m_bIsChanged.
SetPtr() [2/2]
template<class T > void Safir::Dob::Typesystem::ObjectContainerImpl< T >::SetPtr (const T_Ptr & ptr)
Set the smart pointer in the container.
This method will set the contained pointer to point to another object. The change flag of the container will be updated.
Parameters
ptr [in] A pointer to the new object to point to.
References Safir::Dob::Typesystem::ContainerBase::m_bIsChanged.