Safir SDK Core: Safir::Time::AceTimeConverter Class Reference
Safir::Time::AceTimeConverter Class Reference
The AceTimeConverter class provides functions to convert to/from ACE time.
#include <Safir/Time/AceTimeConverter.h>
Static Public Member Functions
static ACE_Time_Value ToAceTime (const Safir::Dob::Typesystem::Si64::Second time)
Get specified time in ACE Time representation.
static ACE_Time_Value ToAceTime (const boost::posix_time::time_duration &duration)
Get specified boost time duration in ACE Time representation.
static ACE_Time_Value ToAceTime (const boost::posix_time::ptime &time)
Get specified boost ptime in ACE Time representation.
static Safir::Dob::Typesystem::Si64::Second ToDouble (const ACE_Time_Value &time)
Convert specified ACE time to a Double.
static boost::posix_time::ptime ToPtime (const ACE_Time_Value &utcTime)
Get specified ACE time in boost::posix_time::ptime representation.
Detailed Description
The AceTimeConverter class provides functions to convert to/from ACE time.
Deprecated:
This class will be removed from Safir SDK Core eventually, make your own copy of it if you need it.
Member Function Documentation
ToAceTime() [1/3]
ACE_Time_Value Safir::Time::AceTimeConverter::ToAceTime (const boost::posix_time::ptime & time) static
Get specified boost ptime in ACE Time representation.
Parameters
[in] time - The time
Returns
The time in ACE_Time_Value
References ToAceTime(), and Safir::Time::TimeProvider::ToDouble().
ToAceTime() [2/3]
ACE_Time_Value Safir::Time::AceTimeConverter::ToAceTime (const boost::posix_time::time_duration & duration) static
Get specified boost time duration in ACE Time representation.
Parameters
[in] duration - The time duration
Returns
The time in ACE_Time_Value
ToAceTime() [3/3]
ACE_Time_Value Safir::Time::AceTimeConverter::ToAceTime (const Safir::Dob::Typesystem::Si64::Second time) static
Get specified time in ACE Time representation.
Parameters
[in] time - The time
Returns
The time in ACE_Time_Value
Referenced by ToAceTime().
ToDouble()
Safir::Dob::Typesystem::Si64::Second Safir::Time::AceTimeConverter::ToDouble (const ACE_Time_Value & time) static
Convert specified ACE time to a Double.
Parameters
[in] time - The ACE time
Returns
Seconds and fraction since jan 1 1970 00:00
Referenced by ToPtime().
ToPtime()
boost::posix_time::ptime Safir::Time::AceTimeConverter::ToPtime (const ACE_Time_Value & utcTime) static
Get specified ACE time in boost::posix_time::ptime representation.
Parameters
[in] utcTime - The UTC time
Returns
The UTC time stored in a boost::posix_time::ptime object
References ToDouble(), and Safir::Time::TimeProvider::ToPtime().