Safir SDK Core: Safir::Dob::Typesystem Namespace Reference
Safir::Dob::Typesystem Namespace Reference
This namespace contains the DOB Typesystem functionality and definitions.
Namespaces
Internal
This namespace contains stuff that is internal to the DOB typesystem.
Members
Functions for getting member information from types.
Operations
Operations on DOB types.
Parameters
Functions for getting parameter information from types.
Si32
32 bit SI-types.
Si64
64 bit SI-types.
ToolSupport
Utilities
Utility functions for users of the DOB type system.
Classes
class ArrayContainer
STL container for arrays of DOB-containers.
class BinaryContainer
Container for Binary.
class ChannelId
Class containing the identity of a channel.
class ConfigurationErrorException
Used when there is an error that implies that there is something wrong in the configuration.
class ContainerBase
Base class for all Containers.
class ContainerProxy
class ContainerProxy< BinaryContainer >
class ContainerProxy< ObjectContainerImpl< Object > >
class ContainerProxy< ObjectContainerImpl< U > >
class ContainerProxy< StringContainer >
class DictionaryContainer
Container class for dictionaries of key value pairs.
class DictionaryContainerBase
Base class for all dictionary containers.
class EntityId
Class containing the identity of an entity.
class EnumerationContainerBase
Base class for containers of enumeration values.
class Exception
This is the base class of all (non-Fundamental) Exceptions.
class FundamentalException
This is the base class of all Fundamental Exceptions.
class GenericObjectSequenceContainer
class GenericObjectSequenceContainerBase
Base class for all object sequences.
class HandlerId
Class containing the identity of a handler.
class IllegalValueException
A parameter in the call was invalid.
class IncompatibleTypesException
This exception is thrown if a class cannot be cast to the expected type.
class InstanceId
Class containing the identity of an instance.
class LibraryExceptions
Contains methods used when passing exceptions across language boundaries.
class NullException
Thrown when an application attempts to get the value of a member that is null.
class Object
The base class for all DOB objects.
class ObjectContainerBase
Base class for all object containers.
class ObjectContainerImpl
Template class for all containers of automatically generated DOB objects.
class ObjectContainerImpl< Object >
This is a specialization of the ObjectContainerImpl template for the case where the template argument is Dob::Typesystem::Object.
class ObjectFactory
This class is an object factory for all automatically generated DOB classes.
class Properties
Functions for getting property information from types and objects.
class ReadOnlyException
Used when someone tries to set a property that is mapped to something that cannot be changed.
class SequenceContainer
class SequenceContainerBase
Container class for sequences of values.
class Serialization
Functions for serializing objects to binary, XML and JSON forms.
class SoftwareViolationException
Meant to be used when something goes very wrong.
class StringContainer
Container for strings (std::wstring).
class ValueContainer
Container for base types.
Typedefs
typedef DotsC_TypeId TypeId
A unique type identifier.
typedef std::vector< TypeId > TypeIdVector
A vector of TypeIds.
typedef DotsC_EnumerationValue EnumerationValue
The ordinal value of an enumeration.
typedef DotsC_MemberType MemberType
An enumeration of all possible types of an object member.
typedef DotsC_CollectionType CollectionType
An enumeration of all possible collection types of an object member.
typedef std::vector< char > BinarySerialization
A type to contain binary serializations of DOB objects.
typedef std::vector< char > Binary
A type to contain binary data.
typedef boost::shared_ptr< Object > ObjectPtr
A smart pointer to an Object.
typedef boost::shared_ptr< const Object > ObjectConstPtr
A smart pointer to a const Object.
typedef Safir::Dob::Typesystem::ObjectContainerImpl< Object > ObjectContainer
Container for DOB Objects.
Container array typedefs
typedef ArrayContainer< BooleanContainer > BooleanContainerArray
An array of DOB-containers containing booleans.
typedef ArrayContainer< Int32Container > Int32ContainerArray
An array of DOB-containers containing 32 bit integers.
typedef ArrayContainer< Int64Container > Int64ContainerArray
An array of DOB-containers containing 64 bit integers.
typedef ArrayContainer< Float32Container > Float32ContainerArray
An array of DOB-containers containing 32 bit floats.
typedef ArrayContainer< Float64Container > Float64ContainerArray
An array of DOB-containers containing 64 bit floats.
typedef ArrayContainer< TypeIdContainer > TypeIdContainerArray
An array of DOB-containers containing TypeIds.
typedef ArrayContainer< InstanceIdContainer > InstanceIdContainerArray
An array of DOB-containers containing InstanceIds.
typedef ArrayContainer< EntityIdContainer > EntityIdContainerArray
An array of DOB-containers containing EntityIds.
typedef ArrayContainer< ChannelIdContainer > ChannelIdContainerArray
An array of DOB-containers containing ChannelIds.
typedef ArrayContainer< HandlerIdContainer > HandlerIdContainerArray
An array of DOB-containers containing HandlerIds.
typedef ArrayContainer< StringContainer > StringContainerArray
An array of DOB-containers containing strings.
typedef Safir::Dob::Typesystem::ArrayContainer< ObjectContainer > ObjectContainerArray
An array of DOB-containers containing DOB-objects.
typedef Safir::Dob::Typesystem::ArrayContainer< BinaryContainer > BinaryContainerArray
An array of DOB-containers containing Binaries.
Base Types
These are the types that all numeric types in the DOB are based on.
They are guaranteed to be of the correct size on all supported platforms.
typedef DotsC_Int32 Int32
32 bit integer type.
typedef DotsC_Int64 Int64
64 bit integer type.
typedef DotsC_Float32 Float32
32 bit floating point type.
typedef DotsC_Float64 Float64
64 bit floating point type.
Type indices.
Types for indices into types.
typedef DotsC_MemberIndex MemberIndex
The index of a member in an object.
typedef DotsC_ArrayIndex ArrayIndex
Index into an array.
typedef DotsC_ParameterIndex ParameterIndex
The index of a parameter in an object.
Basic type container typedefs
typedef SequenceContainer< std::wstring > StringSequenceContainer
A container containing string values.
typedef SequenceContainer< bool > BooleanSequenceContainer
A container containing boolean values.
typedef SequenceContainer< Int32 > Int32SequenceContainer
A container containing 32 bit integer values.
typedef SequenceContainer< Int64 > Int64SequenceContainer
A container containing 64 bit integer values.
typedef SequenceContainer< Float32 > Float32SequenceContainer
A container containing 32 bit floating point values.
typedef SequenceContainer< Float64 > Float64SequenceContainer
A container containing 64 bit floating point values.
typedef SequenceContainer< TypeId > TypeIdSequenceContainer
A container containing TypeId values.
typedef SequenceContainer< InstanceId > InstanceIdSequenceContainer
A container containing InstanceId values.
typedef SequenceContainer< EntityId > EntityIdSequenceContainer
A container containing EntityId values.
typedef SequenceContainer< ChannelId > ChannelIdSequenceContainer
A container containing ChannelId values.
typedef SequenceContainer< HandlerId > HandlerIdSequenceContainer
A container containing HandlerId values.
typedef SequenceContainer< Binary > BinarySequenceContainer
A container containing Binary values.
typedef GenericObjectSequenceContainer< Object > ObjectSequenceContainer
A container containing Object values.
typedef ValueContainer< bool > BooleanContainer
A container containing boolean values.
typedef ValueContainer< Int32 > Int32Container
A container containing 32 bit integer values.
typedef ValueContainer< Int64 > Int64Container
A container containing 64 bit integer values.
typedef ValueContainer< Float32 > Float32Container
A container containing 32 bit floating point values.
typedef ValueContainer< Float64 > Float64Container
A container containing 64 bit floating point values.
typedef ValueContainer< TypeId > TypeIdContainer
A container containing TypeId values.
typedef ValueContainer< InstanceId > InstanceIdContainer
A container containing InstanceId values.
typedef ValueContainer< EntityId > EntityIdContainer
A container containing EntityId values.
typedef ValueContainer< ChannelId > ChannelIdContainer
A container containing ChannelId values.
typedef ValueContainer< HandlerId > HandlerIdContainer
A container containing HandlerId values.
Functions
static std::wostream & operator<< (std::wostream &out, const ChannelId &channelId)
std::size_t hash_value (const Safir::Dob::Typesystem::ChannelId &val)
static bool IsChanged (const ContainerBase &container)
Check if a container is changed.
static bool operator== (const ContainerProxy< ChannelIdContainer > &first, const ChannelId &second)
static bool operator!= (const ContainerProxy< ChannelIdContainer > &first, const ChannelId &second)
static bool operator== (const ContainerProxy< HandlerIdContainer > &first, const HandlerId &second)
static bool operator!= (const ContainerProxy< HandlerIdContainer > &first, const HandlerId &second)
static bool operator== (const ContainerProxy< InstanceIdContainer > &first, const InstanceId &second)
static bool operator!= (const ContainerProxy< InstanceIdContainer > &first, const InstanceId &second)
static bool operator== (const ContainerProxy< EntityIdContainer > &first, const EntityId &second)
static bool operator!= (const ContainerProxy< EntityIdContainer > &first, const EntityId &second)
static bool operator== (const std::wstring &first, const ContainerProxy< StringContainer > &second)
static bool operator!= (const std::wstring &first, const ContainerProxy< StringContainer > &second)
static bool operator== (const Binary &first, const ContainerProxy< BinaryContainer > &second)
static bool operator!= (const Binary &first, const ContainerProxy< BinaryContainer > &second)
static std::wostream & operator<< (std::wostream &out, const EntityId &entityId)
std::size_t hash_value (const Safir::Dob::Typesystem::EntityId &eid)
static std::wostream & operator<< (std::wostream &out, const HandlerId &handlerId)
std::size_t hash_value (const Safir::Dob::Typesystem::HandlerId &val)
static std::wostream & operator<< (std::wostream &out, const InstanceId &instanceId)
std::size_t hash_value (const Safir::Dob::Typesystem::InstanceId &val)
Detailed Description
This namespace contains the DOB Typesystem functionality and definitions.
Typedef Documentation
ArrayIndex
typedef DotsC_ArrayIndex Safir::Dob::Typesystem::ArrayIndex
Index into an array.
DOB-object arrays are indexed using this type. Note: Even though this is a signed 32 bit integer only the positive values are valid.
See also
Dob::Typesystem::Members
Binary
typedef std::vector<char> Safir::Dob::Typesystem::Binary
A type to contain binary data.
BinaryContainerArray
typedef Safir::Dob::Typesystem::ArrayContainer<BinaryContainer> Safir::Dob::Typesystem::BinaryContainerArray
An array of DOB-containers containing Binaries.
BinarySequenceContainer
typedef SequenceContainer<Binary> Safir::Dob::Typesystem::BinarySequenceContainer
A container containing Binary values.
BinarySerialization
typedef std::vector<char> Safir::Dob::Typesystem::BinarySerialization
A type to contain binary serializations of DOB objects.
Note: If you need to get hold of a "raw" C-pointer to the data * use &binary[0]. See Effective STL Item 16 for more info.
BooleanContainer
typedef ValueContainer<bool> Safir::Dob::Typesystem::BooleanContainer
A container containing boolean values.
BooleanContainerArray
typedef ArrayContainer<BooleanContainer> Safir::Dob::Typesystem::BooleanContainerArray
An array of DOB-containers containing booleans.
BooleanSequenceContainer
typedef SequenceContainer<bool> Safir::Dob::Typesystem::BooleanSequenceContainer
A container containing boolean values.
ChannelIdContainer
typedef ValueContainer<ChannelId> Safir::Dob::Typesystem::ChannelIdContainer
A container containing ChannelId values.
ChannelIdContainerArray
typedef ArrayContainer<ChannelIdContainer> Safir::Dob::Typesystem::ChannelIdContainerArray
An array of DOB-containers containing ChannelIds.
ChannelIdSequenceContainer
typedef SequenceContainer<ChannelId> Safir::Dob::Typesystem::ChannelIdSequenceContainer
A container containing ChannelId values.
CollectionType
typedef DotsC_CollectionType Safir::Dob::Typesystem::CollectionType
An enumeration of all possible collection types of an object member.
The values of this enumeration is defined in the file Safir/Dob/Typesystem/LanguageInterfaceDefs.h.
See also
Safir/Dob/Typesystem/LanguageInterfaceDefs.h
EntityIdContainer
typedef ValueContainer<EntityId> Safir::Dob::Typesystem::EntityIdContainer
A container containing EntityId values.
EntityIdContainerArray
typedef ArrayContainer<EntityIdContainer> Safir::Dob::Typesystem::EntityIdContainerArray
An array of DOB-containers containing EntityIds.
EntityIdSequenceContainer
typedef SequenceContainer<EntityId> Safir::Dob::Typesystem::EntityIdSequenceContainer
A container containing EntityId values.
EnumerationValue
typedef DotsC_EnumerationValue Safir::Dob::Typesystem::EnumerationValue
The ordinal value of an enumeration.
When you use the set or get the ordinal on an EnumerationContainer you will get values of this kind. Normally you will not need to use this, instead use the real enumeration values through GetVal() and SetVal(). Note: Even though this is a signed 32 bit integer only the positive values are valid.
See also
Dob::Typesystem::EnumerationContainerBase::GetOrdinal
Dob::Typesystem::EnumerationContainerBase::SetOrdinal
Float32
typedef DotsC_Float32 Safir::Dob::Typesystem::Float32
32 bit floating point type.
This type is guaranteed to be 32 bits on all platforms.
Float32Container
typedef ValueContainer<Float32> Safir::Dob::Typesystem::Float32Container
A container containing 32 bit floating point values.
Float32ContainerArray
typedef ArrayContainer<Float32Container> Safir::Dob::Typesystem::Float32ContainerArray
An array of DOB-containers containing 32 bit floats.
Float32SequenceContainer
typedef SequenceContainer<Float32> Safir::Dob::Typesystem::Float32SequenceContainer
A container containing 32 bit floating point values.
Float64
typedef DotsC_Float64 Safir::Dob::Typesystem::Float64
64 bit floating point type.
This type is guaranteed to be 64 bits on all platforms.
Float64Container
typedef ValueContainer<Float64> Safir::Dob::Typesystem::Float64Container
A container containing 64 bit floating point values.
Float64ContainerArray
typedef ArrayContainer<Float64Container> Safir::Dob::Typesystem::Float64ContainerArray
An array of DOB-containers containing 64 bit floats.
Float64SequenceContainer
typedef SequenceContainer<Float64> Safir::Dob::Typesystem::Float64SequenceContainer
A container containing 64 bit floating point values.
HandlerIdContainer
typedef ValueContainer<HandlerId> Safir::Dob::Typesystem::HandlerIdContainer
A container containing HandlerId values.
HandlerIdContainerArray
typedef ArrayContainer<HandlerIdContainer> Safir::Dob::Typesystem::HandlerIdContainerArray
An array of DOB-containers containing HandlerIds.
HandlerIdSequenceContainer
typedef SequenceContainer<HandlerId> Safir::Dob::Typesystem::HandlerIdSequenceContainer
A container containing HandlerId values.
InstanceIdContainer
typedef ValueContainer<InstanceId> Safir::Dob::Typesystem::InstanceIdContainer
A container containing InstanceId values.
InstanceIdContainerArray
typedef ArrayContainer<InstanceIdContainer> Safir::Dob::Typesystem::InstanceIdContainerArray
An array of DOB-containers containing InstanceIds.
InstanceIdSequenceContainer
typedef SequenceContainer<InstanceId> Safir::Dob::Typesystem::InstanceIdSequenceContainer
A container containing InstanceId values.
Int32
typedef DotsC_Int32 Safir::Dob::Typesystem::Int32
32 bit integer type.
This type is guaranteed to be 32 bits on all platforms.
Int32Container
typedef ValueContainer<Int32> Safir::Dob::Typesystem::Int32Container
A container containing 32 bit integer values.
Int32ContainerArray
typedef ArrayContainer<Int32Container> Safir::Dob::Typesystem::Int32ContainerArray
An array of DOB-containers containing 32 bit integers.
Int32SequenceContainer
typedef SequenceContainer<Int32> Safir::Dob::Typesystem::Int32SequenceContainer
A container containing 32 bit integer values.
Int64
typedef DotsC_Int64 Safir::Dob::Typesystem::Int64
64 bit integer type.
This type is guaranteed to be 64 bits on all platforms.
Int64Container
typedef ValueContainer<Int64> Safir::Dob::Typesystem::Int64Container
A container containing 64 bit integer values.
Int64ContainerArray
typedef ArrayContainer<Int64Container> Safir::Dob::Typesystem::Int64ContainerArray
An array of DOB-containers containing 64 bit integers.
Int64SequenceContainer
typedef SequenceContainer<Int64> Safir::Dob::Typesystem::Int64SequenceContainer
A container containing 64 bit integer values.
MemberIndex
typedef DotsC_MemberIndex Safir::Dob::Typesystem::MemberIndex
The index of a member in an object.
Members in objects are ordered according to the order they appear in the dou-file. However, do not rely on this, but use the Member-operations to get hold of indices if you need them. Note: Even though this is a signed 32 bit integer only the positive values are valid.
See also
Dob::Typesystem::Members
MemberType
typedef DotsC_MemberType Safir::Dob::Typesystem::MemberType
An enumeration of all possible types of an object member.
The values of this enumeration is defined in the file Safir/Dob/Typesystem/LanguageInterfaceDefs.h.
See also
Safir/Dob/Typesystem/LanguageInterfaceDefs.h
ObjectConstPtr
typedef boost::shared_ptr< const Object > Safir::Dob::Typesystem::ObjectConstPtr
A smart pointer to a const Object.
ObjectContainer
typedef Safir::Dob::Typesystem::ObjectContainerImpl<Object> Safir::Dob::Typesystem::ObjectContainer
Container for DOB Objects.
This typedef defines an ObjectContainer that contains an Object... (This is also the reason that the object container template is called ObjectContainerImpl. The name ObjectContainer must be reserved for the container that contains the class Object... But there should be no need for you to worry about this...)
ObjectContainerArray
typedef Safir::Dob::Typesystem::ArrayContainer<ObjectContainer> Safir::Dob::Typesystem::ObjectContainerArray
An array of DOB-containers containing DOB-objects.
ObjectPtr
typedef boost::shared_ptr< Object > Safir::Dob::Typesystem::ObjectPtr
A smart pointer to an Object.
ObjectSequenceContainer
typedef GenericObjectSequenceContainer<Object> Safir::Dob::Typesystem::ObjectSequenceContainer
A container containing Object values.
ParameterIndex
typedef DotsC_ParameterIndex Safir::Dob::Typesystem::ParameterIndex
The index of a parameter in an object.
Parameters in objects are ordered according to the order they appear in the dou-file. However, do not rely on this, but use the Parameter-operations to get hold of indices if you need them. Note: Even though this is a signed 32 bit integer only the positive values are valid.
See also
Dob::Typesystem::Parameters
StringContainerArray
typedef ArrayContainer<StringContainer> Safir::Dob::Typesystem::StringContainerArray
An array of DOB-containers containing strings.
StringSequenceContainer
typedef SequenceContainer<std::wstring> Safir::Dob::Typesystem::StringSequenceContainer
A container containing string values.
TypeId
typedef DotsC_TypeId Safir::Dob::Typesystem::TypeId
A unique type identifier.
A 64 bit integer that uniquely identifies a Dob type. This is in fact 64 bits of an MD5 of the type name and its namespace.
TypeIdContainer
typedef ValueContainer<TypeId> Safir::Dob::Typesystem::TypeIdContainer
A container containing TypeId values.
TypeIdContainerArray
typedef ArrayContainer<TypeIdContainer> Safir::Dob::Typesystem::TypeIdContainerArray
An array of DOB-containers containing TypeIds.
TypeIdSequenceContainer
typedef SequenceContainer<TypeId> Safir::Dob::Typesystem::TypeIdSequenceContainer
A container containing TypeId values.
TypeIdVector
typedef std::vector<TypeId> Safir::Dob::Typesystem::TypeIdVector
A vector of TypeIds.
Function Documentation
hash_value() [1/4]
std::size_t Safir::Dob::Typesystem::hash_value (const Safir::Dob::Typesystem::EntityId & eid)
References Safir::Dob::Typesystem::EntityId::GetInstanceId(), Safir::Dob::Typesystem::InstanceId::GetRawValue(), and Safir::Dob::Typesystem::EntityId::GetTypeId().
hash_value() [2/4]
std::size_t Safir::Dob::Typesystem::hash_value (const Safir::Dob::Typesystem::HandlerId & val)
References Safir::Dob::Typesystem::HandlerId::GetRawValue().
hash_value() [3/4]
std::size_t Safir::Dob::Typesystem::hash_value (const Safir::Dob::Typesystem::ChannelId & val)
References Safir::Dob::Typesystem::ChannelId::GetRawValue().
hash_value() [4/4]
std::size_t Safir::Dob::Typesystem::hash_value (const Safir::Dob::Typesystem::InstanceId & val)
References Safir::Dob::Typesystem::InstanceId::GetRawValue().
IsChanged()
static bool Safir::Dob::Typesystem::IsChanged (const ContainerBase & container) static
Check if a container is changed.
This meant for use with stuff in std::algorithms. All it does is call IsChanged on the container.
Parameters
container [in] - The container to check.
Returns
True if the container has changed.
References Safir::Dob::Typesystem::ContainerBase::IsChanged().
Referenced by Safir::Dob::Entity::GetTypeId(), Safir::Dob::Message::GetTypeId(), Safir::Dob::Parametrization::GetTypeId(), Safir::Dob::Item::GetTypeId(), Safir::Dob::Response::GetTypeId(), Safir::Dob::Service::GetTypeId(), Safir::Dob::Struct::GetTypeId(), Safir::Dob::PersistentDataReady::GetTypeId(), Safir::Dob::SuccessResponse::GetTypeId(), Safir::Dob::QueueParameters::GetTypeId(), Safir::Dob::PersistentDataStatus::GetTypeId(), Safir::Control::Parameters::GetTypeId(), Safir::Utilities::ForEach::FullResponse::GetTypeId(), Safir::Dob::EntityIdResponse::GetTypeId(), Safir::Control::Status::GetTypeId(), Safir::Dob::CreateRoutineParameters::GetTypeId(), Safir::Control::Command::GetTypeId(), Safir::Time::LibraryParameters::GetTypeId(), Safir::Websocket::Parameters::GetTypeId(), Safir::Websocket::Typesystem::TypeHierarchy::GetTypeId(), Safir::Utilities::ForEach::DeleteRequest::GetTypeId(), Safir::Dob::ErrorListResponse::GetTypeId(), Safir::Dob::ConnectionInfo::GetTypeId(), Safir::Dob::ErrorResponse::GetTypeId(), Safir::Dob::ProcessInfo::GetTypeId(), Safir::Dob::NodeInfo::GetTypeId(), Safir::Application::BackdoorCommand::GetTypeId(), Safir::Dob::ThisNodeParameters::GetTypeId(), Safir::Utilities::ForEach::BriefResponse::GetTypeId(), Safir::Utilities::ForEach::UpdateRequest::GetTypeId(), Safir::Utilities::ForEach::DeleteAllRequest::GetTypeId(), Safir::Dob::Typesystem::Object::GetTypeId(), Safir::Websocket::Typesystem::EnumType::GetTypeId(), Safir::Dob::QueueRule::GetTypeId(), Safir::Websocket::Typesystem::ClassType::GetTypeId(), Safir::Websocket::Typesystem::Member::GetTypeId(), Safir::Dob::ResponseErrorInfo::GetTypeId(), Safir::Dob::PersistenceParameters::GetTypeId(), Safir::Dob::NodeParameters::GetTypeId(), Safir::Dob::NodeType::GetTypeId(), Safir::Dob::ResponseGeneralErrorCodes::GetTypeId(), and Safir::Dob::Typesystem::ArrayContainer< ResponseErrorInfoContainer >::IsChanged().
operator!=() [1/6]
static bool Safir::Dob::Typesystem::operator!= (const ContainerProxy< ChannelIdContainer > & first, const ChannelId & second) static
operator!=() [2/6]
static bool Safir::Dob::Typesystem::operator!= (const ContainerProxy< HandlerIdContainer > & first, const HandlerId & second) static
operator!=() [3/6]
static bool Safir::Dob::Typesystem::operator!= (const ContainerProxy< InstanceIdContainer > & first, const InstanceId & second) static
operator!=() [4/6]
static bool Safir::Dob::Typesystem::operator!= (const ContainerProxy< EntityIdContainer > & first, const EntityId & second) static
operator!=() [5/6]
static bool Safir::Dob::Typesystem::operator!= (const std::wstring & first, const ContainerProxy< StringContainer > & second) static
operator!=() [6/6]
static bool Safir::Dob::Typesystem::operator!= (const Binary & first, const ContainerProxy< BinaryContainer > & second) static
operator<<() [1/4]
static std::wostream& Safir::Dob::Typesystem::operator<< (std::wostream & out, const EntityId & entityId) static
References Safir::Dob::Typesystem::EntityId::ToString().
operator<<() [2/4]
static std::wostream& Safir::Dob::Typesystem::operator<< (std::wostream & out, const HandlerId & handlerId) static
References Safir::Dob::Typesystem::HandlerId::ToString().
operator<<() [3/4]
static std::wostream& Safir::Dob::Typesystem::operator<< (std::wostream & out, const ChannelId & channelId) static
References Safir::Dob::Typesystem::ChannelId::ToString().
operator<<() [4/4]
static std::wostream& Safir::Dob::Typesystem::operator<< (std::wostream & out, const InstanceId & instanceId) static
References Safir::Dob::Typesystem::InstanceId::ToString().
operator==() [1/6]
static bool Safir::Dob::Typesystem::operator== (const ContainerProxy< ChannelIdContainer > & first, const ChannelId & second) static
operator==() [2/6]
static bool Safir::Dob::Typesystem::operator== (const ContainerProxy< HandlerIdContainer > & first, const HandlerId & second) static
operator==() [3/6]
static bool Safir::Dob::Typesystem::operator== (const ContainerProxy< InstanceIdContainer > & first, const InstanceId & second) static
operator==() [4/6]
static bool Safir::Dob::Typesystem::operator== (const ContainerProxy< EntityIdContainer > & first, const EntityId & second) static
operator==() [5/6]
static bool Safir::Dob::Typesystem::operator== (const std::wstring & first, const ContainerProxy< StringContainer > & second) static
operator==() [6/6]
static bool Safir::Dob::Typesystem::operator== (const Binary & first, const ContainerProxy< BinaryContainer > & second) static