Safir SDK Core: Safir::Dob::Typesystem::ContainerProxy< StringContainer > Class Template Reference
Safir::Dob::Typesystem::ContainerProxy< StringContainer > Class Template Reference
#include <Safir/Dob/Typesystem/ContainerProxies.h>
Public Types
typedef StringContainer::ContainedType ContainedType
Public Member Functions
ContainerProxy (StringContainer &container)
ContainerProxy & operator= (const ContainerProxy &other)
ContainerProxy & operator= (const ContainedType &other)
operator const ContainedType & () const
bool IsNull () const
void SetNull ()
bool IsChanged () const
void SetChanged (const bool changed)
void SetVal (const ContainedType &value)
const ContainedType & GetVal () const
Int32 Utf8StringLength () const
const std::string & Utf8String () const
void Copy (const ContainerProxy &that)
ContainerProxy & operator+= (const ContainedType &val)
bool operator== (const ContainedType &val) const
bool operator!= (const ContainedType &val) const
const StringContainer & GetContainer () const
StringContainer & GetContainer ()
Member Typedef Documentation
ContainedType
typedef StringContainer::ContainedType Safir::Dob::Typesystem::ContainerProxy< StringContainer >::ContainedType
Constructor & Destructor Documentation
ContainerProxy()
Safir::Dob::Typesystem::ContainerProxy< StringContainer >::ContainerProxy (StringContainer & container) explicit
Member Function Documentation
Copy()
void Safir::Dob::Typesystem::ContainerProxy< StringContainer >::Copy (const ContainerProxy< StringContainer > & that)
GetContainer() [1/2]
const StringContainer& Safir::Dob::Typesystem::ContainerProxy< StringContainer >::GetContainer () const
GetContainer() [2/2]
StringContainer& Safir::Dob::Typesystem::ContainerProxy< StringContainer >::GetContainer ()
GetVal()
const ContainedType& Safir::Dob::Typesystem::ContainerProxy< StringContainer >::GetVal () const
IsChanged()
bool Safir::Dob::Typesystem::ContainerProxy< StringContainer >::IsChanged () const
IsNull()
bool Safir::Dob::Typesystem::ContainerProxy< StringContainer >::IsNull () const
operator const ContainedType &()
Safir::Dob::Typesystem::ContainerProxy< StringContainer >::operator const ContainedType & () const
operator!=()
bool Safir::Dob::Typesystem::ContainerProxy< StringContainer >::operator!= (const ContainedType & val) const
operator+=()
ContainerProxy& Safir::Dob::Typesystem::ContainerProxy< StringContainer >::operator+= (const ContainedType & val)
References Safir::Dob::Typesystem::ContainerProxy< T >::GetVal(), and Safir::Dob::Typesystem::ContainerProxy< T >::SetVal().
operator=() [1/2]
ContainerProxy& Safir::Dob::Typesystem::ContainerProxy< StringContainer >::operator= (const ContainerProxy< StringContainer > & other)
References Safir::Dob::Typesystem::ContainerProxy< T >::GetVal(), Safir::Dob::Typesystem::ContainerProxy< T >::IsNull(), and Safir::Dob::Typesystem::ContainerProxy< T >::SetNull().
operator=() [2/2]
ContainerProxy& Safir::Dob::Typesystem::ContainerProxy< StringContainer >::operator= (const ContainedType & other)
References Safir::Dob::Typesystem::ContainerProxy< T >::SetVal().
operator==()
bool Safir::Dob::Typesystem::ContainerProxy< StringContainer >::operator== (const ContainedType & val) const
SetChanged()
void Safir::Dob::Typesystem::ContainerProxy< StringContainer >::SetChanged (const bool changed)
SetNull()
void Safir::Dob::Typesystem::ContainerProxy< StringContainer >::SetNull ()
SetVal()
void Safir::Dob::Typesystem::ContainerProxy< StringContainer >::SetVal (const ContainedType & value)
Utf8String()
const std::string& Safir::Dob::Typesystem::ContainerProxy< StringContainer >::Utf8String () const
Utf8StringLength()
Int32 Safir::Dob::Typesystem::ContainerProxy< StringContainer >::Utf8StringLength () const