Safir SDK Core: Safir::Dob::Typesystem::SequenceContainerBase< T > Class Template Reference
Safir::Dob::Typesystem::SequenceContainerBase< T > Class Template Reference
Container class for sequences of values.
#include <Safir/Dob/Typesystem/SequenceContainer.h>
Public Types
typedef T ContainedType
typedef boost::container::vector< T > StorageType
typedef StorageType::const_iterator const_iterator
Public Member Functions
SequenceContainerBase ()
Default Constructor.
virtual bool IsNull () const
Is the container set to null?
virtual void SetNull ()
Set the container to null.
size_t size () const
size - Get the size of the sequence, i.e number of contained values.
bool empty () const
empty - Check if sequence is empty.
const ContainedType & front () const
front - Get a const reference to the first value in the sequence.
const ContainedType & back () const
back - Get a const reference to the last value in the sequence.
const_iterator begin () const
begin - Get const_iterator pointing to the first element in the sequence.
const_iterator end () const
end - Get const_iterator pointing past the last element in the sequence.
void clear ()
clear - Clear the sequence, i.e remove all values.
const ContainedType & operator[] (size_t index) const
operator [] - Get const reference to the value with specified index.
const ContainedType & at (size_t index) const
operator [] - Get const reference to the value with specified index.
void push_back (const ContainedType &val)
push_back - Insert a new value last in the sequence.
void SetVal (size_t index, const ContainedType &val)
SetVal - Update a specific value.
const ContainedType & GetVal (size_t index) const
GetVal - Get const reference to the value with specified index.
void InsertAt (size_t index, const ContainedType &value)
InsertAt - Insert a new value at specified index.
void EraseAt (size_t index)
EraseAt - Erase a value at specified index.
virtual void Copy (const ContainerBase &that)
Copy - Copy all the members from "that" into "this".
Public Member Functions inherited from Safir::Dob::Typesystem::ContainerBase
ContainerBase ()
Default Constructor.
virtual ~ContainerBase ()
Virtual destructor.
virtual bool IsChanged () const
Is the change flag set on the container?
virtual void SetChanged (const bool changed)
Set the containers change flag.
Additional Inherited Members
Protected Member Functions inherited from Safir::Dob::Typesystem::ContainerBase
ContainerBase & operator= (const ContainerBase &other)
Copy assignment operator.
Protected Attributes inherited from Safir::Dob::Typesystem::ContainerBase
bool m_bIsChanged
The variable containing the change flag.
Detailed Description
template<class T>
class Safir::Dob::Typesystem::SequenceContainerBase< T >
Container class for sequences of values.
A sequence is a collection of values that can dynamically grow or shrink in size. The whole container has a change flag that will automatically be set when values are added, removed or changed. Values in a sequence cannot be null and does not have change flags.
Member Typedef Documentation
const_iterator
template<class T> typedef StorageType::const_iterator Safir::Dob::Typesystem::SequenceContainerBase< T >::const_iterator
ContainedType
template<class T> typedef T Safir::Dob::Typesystem::SequenceContainerBase< T >::ContainedType
StorageType
template<class T> typedef boost::container::vector<T> Safir::Dob::Typesystem::SequenceContainerBase< T >::StorageType
Constructor & Destructor Documentation
SequenceContainerBase()
template<class T> Safir::Dob::Typesystem::SequenceContainerBase< T >::SequenceContainerBase ()
Default Constructor.
Construct a container that is not changed and not null.
Member Function Documentation
at()
template<class T> const ContainedType& Safir::Dob::Typesystem::SequenceContainerBase< T >::at (size_t index) const
operator [] - Get const reference to the value with specified index.
Parameters
index [in] - Index of the value to get.
Returns
Const reference to a value.
Exceptions
std::out_of_range exception if index is not in range
back()
template<class T> const ContainedType& Safir::Dob::Typesystem::SequenceContainerBase< T >::back () const
back - Get a const reference to the last value in the sequence.
Returns
Reference to last value.
begin()
template<class T> const_iterator Safir::Dob::Typesystem::SequenceContainerBase< T >::begin () const
begin - Get const_iterator pointing to the first element in the sequence.
Returns
const_iterator.
clear()
template<class T> void Safir::Dob::Typesystem::SequenceContainerBase< T >::clear ()
clear - Clear the sequence, i.e remove all values.
After a call to clear the sequence will be empty but not automatically set to null.
Referenced by Safir::Dob::Typesystem::SequenceContainerBase< boost::shared_ptr< EnumType > >::SetNull().
Copy()
template<class T> virtual void Safir::Dob::Typesystem::SequenceContainerBase< T >::Copy (const ContainerBase & that) virtual
Copy - Copy all the members from "that" into "this".
Types must be the same for this to work!
Parameters
that [in] - The object to copy into this.
Exceptions
SoftwareViolationException If the types are not of the same kind.
Implements Safir::Dob::Typesystem::ContainerBase.
Referenced by Safir::Dob::Typesystem::SequenceContainerBase< boost::shared_ptr< EnumType > >::Copy().
empty()
template<class T> bool Safir::Dob::Typesystem::SequenceContainerBase< T >::empty () const
empty - Check if sequence is empty.
Returns
True if sequence is empty, else false.
Referenced by Safir::Dob::Typesystem::SequenceContainerBase< boost::shared_ptr< EnumType > >::IsNull().
end()
template<class T> const_iterator Safir::Dob::Typesystem::SequenceContainerBase< T >::end () const
end - Get const_iterator pointing past the last element in the sequence.
Returns
const_iterator.
EraseAt()
template<class T> void Safir::Dob::Typesystem::SequenceContainerBase< T >::EraseAt (size_t index)
EraseAt - Erase a value at specified index.
The sequence will shrink.
Parameters
index [in] - Index of the value to be removed.
front()
template<class T> const ContainedType& Safir::Dob::Typesystem::SequenceContainerBase< T >::front () const
front - Get a const reference to the first value in the sequence.
Returns
Reference to first value.
GetVal()
template<class T> const ContainedType& Safir::Dob::Typesystem::SequenceContainerBase< T >::GetVal (size_t index) const
GetVal - Get const reference to the value with specified index.
Parameters
index [in] - Index of the value to get.
Returns
Const reference to a value.
InsertAt()
template<class T> void Safir::Dob::Typesystem::SequenceContainerBase< T >::InsertAt (size_t index, const ContainedType & value)
InsertAt - Insert a new value at specified index.
The sequence size will grow.
Parameters
index [in] - Index of the new value.
value [in] - Value to insert.
IsNull()
template<class T> virtual bool Safir::Dob::Typesystem::SequenceContainerBase< T >::IsNull () const virtual
Is the container set to null?
Returns
True if the container is set to null.
Implements Safir::Dob::Typesystem::ContainerBase.
operator[]()
template<class T> const ContainedType& Safir::Dob::Typesystem::SequenceContainerBase< T >::operator[] (size_t index) const
operator [] - Get const reference to the value with specified index.
Note that no checks are made to see whether index is inside range.
Parameters
index [in] - Index of the value to get.
Returns
Const reference to a value.
push_back()
template<class T> void Safir::Dob::Typesystem::SequenceContainerBase< T >::push_back (const ContainedType & val)
push_back - Insert a new value last in the sequence.
If the sequence was null before it will no longer be null after a call to push_back.
Parameters
val [in] - Value to be inserted.
SetNull()
template<class T> virtual void Safir::Dob::Typesystem::SequenceContainerBase< T >::SetNull () virtual
Set the container to null.
Implements Safir::Dob::Typesystem::ContainerBase.
SetVal()
template<class T> void Safir::Dob::Typesystem::SequenceContainerBase< T >::SetVal (size_t index, const ContainedType & val)
SetVal - Update a specific value.
Will not add new values.
Parameters
index [in] - Index of the value to set.
val [in] - Value to set.
size()
template<class T> size_t Safir::Dob::Typesystem::SequenceContainerBase< T >::size () const
size - Get the size of the sequence, i.e number of contained values.
Returns
The number of values in the sequence.