Safir SDK Core: Safir::Dob::Typesystem::EnumerationContainerBase Class Reference
Safir::Dob::Typesystem::EnumerationContainerBase Class Reference abstract
Base class for containers of enumeration values.
#include <Safir/Dob/Typesystem/EnumerationContainerBase.h>
Public Member Functions
EnumerationContainerBase ()
Default Constructor.
virtual void SetOrdinal (const EnumerationValue value)=0
Set the ordinal value of the enumeration container.
virtual EnumerationValue GetOrdinal () const =0
Get the ordinal value of the enumeration container.
virtual bool IsNull () const
Is the container set to null?
virtual void SetNull ()
Set the container to null.
virtual void Copy (const ContainerBase &that)
Virtual assignment.
Public Member Functions inherited from Safir::Dob::Typesystem::ContainerBase
ContainerBase ()
Default Constructor.
virtual ~ContainerBase ()
Virtual destructor.
virtual bool IsChanged () const
Is the change flag set on the container?
virtual void SetChanged (const bool changed)
Set the containers change flag.
Protected Member Functions
EnumerationContainerBase & operator= (const EnumerationContainerBase &other)
Copy assignment operator.
Protected Member Functions inherited from Safir::Dob::Typesystem::ContainerBase
ContainerBase & operator= (const ContainerBase &other)
Copy assignment operator.
Protected Attributes
bool m_bIsNull
The null flag for the enumeration container.
EnumerationValue m_Value
The value of the enumeration container.
Protected Attributes inherited from Safir::Dob::Typesystem::ContainerBase
bool m_bIsChanged
The variable containing the change flag.
Friends
class Safir::Dob::Typesystem::Internal::BlobOperations
Detailed Description
Base class for containers of enumeration values.
The containers for enumerations are defined in the automatically generated code, but this class defines the common functionality for them. Enumeration containers really store the ordinal values (integer representation of the enumeration), and this class has methods for setting and getting the ordinal. The derived class (in the generated code) has methods for setting and getting the value as an enumeration value. Most applications should not use the GetOrdinal/SetOrdinal functions, but should use the SetVal and GetVal methods defined in the derived classes.
Constructor & Destructor Documentation
EnumerationContainerBase()
Safir::Dob::Typesystem::EnumerationContainerBase::EnumerationContainerBase ()
Default Constructor.
Constructs an enumeration container that is null and not changed.
References GetOrdinal(), and SetOrdinal().
Member Function Documentation
Copy()
virtual void Safir::Dob::Typesystem::EnumerationContainerBase::Copy (const ContainerBase & that) virtual
Virtual assignment.
Copy all the members from "that" into "this". Types must be the same for this to work!
Parameters
that [in] - The object to copy into this.
Exceptions
SoftwareViolationException If the types are not of the same kind.
Implements Safir::Dob::Typesystem::ContainerBase.
References __WFILE__.
GetOrdinal()
virtual EnumerationValue Safir::Dob::Typesystem::EnumerationContainerBase::GetOrdinal () const pure virtual
Get the ordinal value of the enumeration container.
Note: Only applications that need to use "anonymous enums" should use this method. All other applications should be using the GetVal method.
Returns
The ordinal value of the container.
Exceptions
NullException The container is null.
Implemented in Safir::Dob::CallbackId::EnumerationContainer, Safir::Utilities::ForEach::ResponseType::EnumerationContainer, Safir::Dob::ConnectionQueueId::EnumerationContainer, Safir::Dob::InjectionKind::EnumerationContainer, Safir::Control::Operation::EnumerationContainer, Safir::Dob::PersistenceBackend::EnumerationContainer, Safir::Dob::DistributionScope::EnumerationContainer, Safir::Dob::InstanceIdPolicy::EnumerationContainer, and Safir::Dob::PersistentDataState::EnumerationContainer.
Referenced by EnumerationContainerBase().
IsNull()
virtual bool Safir::Dob::Typesystem::EnumerationContainerBase::IsNull () const virtual
Is the container set to null?
Returns
True if the container is set to null.
Implements Safir::Dob::Typesystem::ContainerBase.
References m_bIsNull.
operator=()
EnumerationContainerBase& Safir::Dob::Typesystem::EnumerationContainerBase::operator= (const EnumerationContainerBase & other) protected
Copy assignment operator.
Parameters
other [in] - The object to copy.
Returns
A reference to this.
References m_bIsNull, m_Value, and Safir::Dob::Typesystem::ContainerBase::operator=().
SetNull()
virtual void Safir::Dob::Typesystem::EnumerationContainerBase::SetNull () virtual
Set the container to null.
Implements Safir::Dob::Typesystem::ContainerBase.
References Safir::Dob::Typesystem::ContainerBase::m_bIsChanged, and m_bIsNull.
SetOrdinal()
virtual void Safir::Dob::Typesystem::EnumerationContainerBase::SetOrdinal (const EnumerationValue value) pure virtual
Set the ordinal value of the enumeration container.
Note: Only applications that need to use "anonymous enums" should use this method. All other applications should be using the SetVal method.
Parameters
value [in] - The new value.
Exceptions
IllegalValueException The value is not in the range of the enumeration.
Implemented in Safir::Dob::CallbackId::EnumerationContainer, Safir::Utilities::ForEach::ResponseType::EnumerationContainer, Safir::Dob::ConnectionQueueId::EnumerationContainer, Safir::Dob::InjectionKind::EnumerationContainer, Safir::Control::Operation::EnumerationContainer, Safir::Dob::PersistenceBackend::EnumerationContainer, Safir::Dob::DistributionScope::EnumerationContainer, Safir::Dob::InstanceIdPolicy::EnumerationContainer, and Safir::Dob::PersistentDataState::EnumerationContainer.
Referenced by EnumerationContainerBase().
Friends And Related Function Documentation
Safir::Dob::Typesystem::Internal::BlobOperations
friend class Safir::Dob::Typesystem::Internal::BlobOperations friend
Member Data Documentation
m_bIsNull
bool Safir::Dob::Typesystem::EnumerationContainerBase::m_bIsNull protected
The null flag for the enumeration container.
Referenced by IsNull(), operator=(), and SetNull().
m_Value
EnumerationValue Safir::Dob::Typesystem::EnumerationContainerBase::m_Value protected
The value of the enumeration container.
This is the ordinal value. Needs to be cast to the correct type in the derived classes.
Referenced by operator=().