Safir SDK Core: Safir::Dob::Typesystem::ContainerProxy< StringContainer > Class Template Reference
Safir::Dob::Typesystem::ContainerProxy< StringContainer > Class Template Reference
#include <Safir/Dob/Typesystem/ContainerProxies.h>
Public Types
typedef StringContainer::ContainedType ContainedType
Public Member Functions
ContainerProxy (StringContainer &container)
ContainerProxy & operator= (const ContainerProxy &other)
ContainerProxy & operator= (const ContainedType &other)
operator const ContainedType & () const
bool IsNull () const
void SetNull ()
bool IsChanged () const
void SetChanged (const bool changed)
void SetVal (const ContainedType &value)
const ContainedType & GetVal () const
Int32 Utf8StringLength () const
const std::string & Utf8String () const
void Copy (const ContainerProxy &that)
ContainerProxy & operator+= (const ContainedType &val)
bool operator== (const ContainedType &val) const
bool operator!= (const ContainedType &val) const
const StringContainer & GetContainer () const
StringContainer & GetContainer ()
Member Typedef Documentation
typedef StringContainer::ContainedType Safir::Dob::Typesystem::ContainerProxy< StringContainer >::ContainedType
Constructor & Destructor Documentation
Safir::Dob::Typesystem::ContainerProxy< StringContainer >::ContainerProxy (StringContainer & container) explicit
Member Function Documentation
void Safir::Dob::Typesystem::ContainerProxy< StringContainer >::Copy (const ContainerProxy< StringContainer > & that)
const StringContainer& Safir::Dob::Typesystem::ContainerProxy< StringContainer >::GetContainer () const
StringContainer& Safir::Dob::Typesystem::ContainerProxy< StringContainer >::GetContainer ()
const ContainedType& Safir::Dob::Typesystem::ContainerProxy< StringContainer >::GetVal () const
bool Safir::Dob::Typesystem::ContainerProxy< StringContainer >::IsChanged () const
bool Safir::Dob::Typesystem::ContainerProxy< StringContainer >::IsNull () const
Safir::Dob::Typesystem::ContainerProxy< StringContainer >::operator const ContainedType & () const
bool Safir::Dob::Typesystem::ContainerProxy< StringContainer >::operator!= (const ContainedType & val) const
ContainerProxy& Safir::Dob::Typesystem::ContainerProxy< StringContainer >::operator+= (const ContainedType & val)
References Safir::Dob::Typesystem::ContainerProxy< T >::GetVal(), and Safir::Dob::Typesystem::ContainerProxy< T >::SetVal().
ContainerProxy& Safir::Dob::Typesystem::ContainerProxy< StringContainer >::operator= (const ContainerProxy< StringContainer > & other)
References Safir::Dob::Typesystem::ContainerProxy< T >::GetVal(), Safir::Dob::Typesystem::ContainerProxy< T >::IsNull(), and Safir::Dob::Typesystem::ContainerProxy< T >::SetNull().
ContainerProxy& Safir::Dob::Typesystem::ContainerProxy< StringContainer >::operator= (const ContainedType & other)
References Safir::Dob::Typesystem::ContainerProxy< T >::SetVal().
bool Safir::Dob::Typesystem::ContainerProxy< StringContainer >::operator== (const ContainedType & val) const
void Safir::Dob::Typesystem::ContainerProxy< StringContainer >::SetChanged (const bool changed)
void Safir::Dob::Typesystem::ContainerProxy< StringContainer >::SetNull ()
void Safir::Dob::Typesystem::ContainerProxy< StringContainer >::SetVal (const ContainedType & value)
const std::string& Safir::Dob::Typesystem::ContainerProxy< StringContainer >::Utf8String () const
Int32 Safir::Dob::Typesystem::ContainerProxy< StringContainer >::Utf8StringLength () const