Safir SDK Core: Safir::Dob::Typesystem::ContainerProxy< BinaryContainer > Class Template Reference
Safir::Dob::Typesystem::ContainerProxy< BinaryContainer > Class Template Reference
#include <Safir/Dob/Typesystem/ContainerProxies.h>
Public Types
typedef BinaryContainer::ContainedType ContainedType
Public Member Functions
ContainerProxy (BinaryContainer &container)
ContainerProxy & operator= (const ContainerProxy &other)
ContainerProxy & operator= (const ContainedType &other)
operator const ContainedType & () const
bool IsNull () const
void SetNull ()
bool IsChanged () const
void SetChanged (const bool changed)
void SetVal (const ContainedType &value)
const ContainedType & GetVal () const
void Copy (const ContainerProxy &that)
bool operator== (const ContainedType &val) const
bool operator!= (const ContainedType &val) const
const BinaryContainer & GetContainer () const
BinaryContainer & GetContainer ()
Member Typedef Documentation
ContainedType
typedef BinaryContainer::ContainedType Safir::Dob::Typesystem::ContainerProxy< BinaryContainer >::ContainedType
Constructor & Destructor Documentation
ContainerProxy()
Safir::Dob::Typesystem::ContainerProxy< BinaryContainer >::ContainerProxy (BinaryContainer & container) explicit
Member Function Documentation
Copy()
void Safir::Dob::Typesystem::ContainerProxy< BinaryContainer >::Copy (const ContainerProxy< BinaryContainer > & that)
GetContainer() [1/2]
const BinaryContainer& Safir::Dob::Typesystem::ContainerProxy< BinaryContainer >::GetContainer () const
GetContainer() [2/2]
BinaryContainer& Safir::Dob::Typesystem::ContainerProxy< BinaryContainer >::GetContainer ()
GetVal()
const ContainedType& Safir::Dob::Typesystem::ContainerProxy< BinaryContainer >::GetVal () const
IsChanged()
bool Safir::Dob::Typesystem::ContainerProxy< BinaryContainer >::IsChanged () const
IsNull()
bool Safir::Dob::Typesystem::ContainerProxy< BinaryContainer >::IsNull () const
operator const ContainedType &()
Safir::Dob::Typesystem::ContainerProxy< BinaryContainer >::operator const ContainedType & () const
operator!=()
bool Safir::Dob::Typesystem::ContainerProxy< BinaryContainer >::operator!= (const ContainedType & val) const
operator=() [1/2]
ContainerProxy& Safir::Dob::Typesystem::ContainerProxy< BinaryContainer >::operator= (const ContainerProxy< BinaryContainer > & other)
References Safir::Dob::Typesystem::ContainerProxy< T >::GetVal(), Safir::Dob::Typesystem::ContainerProxy< T >::IsNull(), and Safir::Dob::Typesystem::ContainerProxy< T >::SetNull().
operator=() [2/2]
ContainerProxy& Safir::Dob::Typesystem::ContainerProxy< BinaryContainer >::operator= (const ContainedType & other)
References Safir::Dob::Typesystem::ContainerProxy< T >::SetVal().
operator==()
bool Safir::Dob::Typesystem::ContainerProxy< BinaryContainer >::operator== (const ContainedType & val) const
SetChanged()
void Safir::Dob::Typesystem::ContainerProxy< BinaryContainer >::SetChanged (const bool changed)
SetNull()
void Safir::Dob::Typesystem::ContainerProxy< BinaryContainer >::SetNull ()
SetVal()
void Safir::Dob::Typesystem::ContainerProxy< BinaryContainer >::SetVal (const ContainedType & value)