Safir SDK Core: Safir::Dob::Typesystem::ContainerProxy< T > Class Template Reference
Safir::Dob::Typesystem::ContainerProxy< T > Class Template Reference
#include <Safir/Dob/Typesystem/ContainerProxies.h>
Public Types
typedef T::ContainedType ContainedType
Public Member Functions
ContainerProxy (T &container)
ContainerProxy & operator= (const ContainerProxy &other)
ContainerProxy & operator= (const ContainedType other)
operator const ContainedType () const
bool IsNull () const
void SetNull ()
bool IsChanged () const
void SetChanged (const bool changed)
void SetVal (const ContainedType value)
const ContainedType GetVal () const
void SetOrdinal (const EnumerationValue value)
EnumerationValue GetOrdinal () const
void Copy (const ContainerProxy &that)
ContainerProxy & operator++ ()
void operator++ (int)
ContainerProxy & operator-- ()
void operator-- (int)
ContainerProxy & operator+= (const ContainedType &val)
ContainerProxy & operator-= (const ContainedType &val)
ContainerProxy & operator*= (const ContainedType &val)
ContainerProxy & operator/= (const ContainedType &val)
const T & GetContainer () const
T & GetContainer ()
Member Typedef Documentation
ContainedType
template<class T> typedef T::ContainedType Safir::Dob::Typesystem::ContainerProxy< T >::ContainedType
Constructor & Destructor Documentation
ContainerProxy()
template<class T> Safir::Dob::Typesystem::ContainerProxy< T >::ContainerProxy (T & container) explicit
Member Function Documentation
Copy()
template<class T> void Safir::Dob::Typesystem::ContainerProxy< T >::Copy (const ContainerProxy< T > & that)
GetContainer() [1/2]
template<class T> const T& Safir::Dob::Typesystem::ContainerProxy< T >::GetContainer () const
GetContainer() [2/2]
template<class T> T& Safir::Dob::Typesystem::ContainerProxy< T >::GetContainer ()
GetOrdinal()
template<class T> EnumerationValue Safir::Dob::Typesystem::ContainerProxy< T >::GetOrdinal () const
GetVal()
template<class T> const ContainedType Safir::Dob::Typesystem::ContainerProxy< T >::GetVal () const
Referenced by Safir::Dob::Typesystem::ContainerProxy< T >::operator*=(), Safir::Dob::Typesystem::ContainerProxy< T >::operator++(), Safir::Dob::Typesystem::ContainerProxy< T >::operator+=(), Safir::Dob::Typesystem::ContainerProxy< StringContainer >::operator+=(), Safir::Dob::Typesystem::ContainerProxy< T >::operator--(), Safir::Dob::Typesystem::ContainerProxy< T >::operator-=(), Safir::Dob::Typesystem::ContainerProxy< T >::operator/=(), Safir::Dob::Typesystem::ContainerProxy< T >::operator=(), Safir::Dob::Typesystem::ContainerProxy< StringContainer >::operator=(), and Safir::Dob::Typesystem::ContainerProxy< BinaryContainer >::operator=().
IsChanged()
template<class T> bool Safir::Dob::Typesystem::ContainerProxy< T >::IsChanged () const
IsNull()
template<class T> bool Safir::Dob::Typesystem::ContainerProxy< T >::IsNull () const
Referenced by Safir::Dob::Typesystem::ContainerProxy< T >::operator=(), Safir::Dob::Typesystem::ContainerProxy< StringContainer >::operator=(), Safir::Dob::Typesystem::ContainerProxy< BinaryContainer >::operator=(), Safir::Dob::Typesystem::ContainerProxy< ObjectContainerImpl< U > >::operator=(), and Safir::Dob::Typesystem::ContainerProxy< ObjectContainerImpl< Object > >::operator=().
operator const ContainedType()
template<class T> Safir::Dob::Typesystem::ContainerProxy< T >::operator const ContainedType () const
operator*=()
template<class T> ContainerProxy& Safir::Dob::Typesystem::ContainerProxy< T >::operator*= (const ContainedType & val)
References Safir::Dob::Typesystem::ContainerProxy< T >::GetVal(), and Safir::Dob::Typesystem::ContainerProxy< T >::SetVal().
operator++() [1/2]
template<class T> ContainerProxy& Safir::Dob::Typesystem::ContainerProxy< T >::operator++ ()
References Safir::Dob::Typesystem::ContainerProxy< T >::GetVal(), and Safir::Dob::Typesystem::ContainerProxy< T >::SetVal().
operator++() [2/2]
template<class T> void Safir::Dob::Typesystem::ContainerProxy< T >::operator++ (int)
operator+=()
template<class T> ContainerProxy& Safir::Dob::Typesystem::ContainerProxy< T >::operator+= (const ContainedType & val)
References Safir::Dob::Typesystem::ContainerProxy< T >::GetVal(), and Safir::Dob::Typesystem::ContainerProxy< T >::SetVal().
operator--() [1/2]
template<class T> ContainerProxy& Safir::Dob::Typesystem::ContainerProxy< T >::operator-- ()
References Safir::Dob::Typesystem::ContainerProxy< T >::GetVal(), and Safir::Dob::Typesystem::ContainerProxy< T >::SetVal().
operator--() [2/2]
template<class T> void Safir::Dob::Typesystem::ContainerProxy< T >::operator-- (int)
operator-=()
template<class T> ContainerProxy& Safir::Dob::Typesystem::ContainerProxy< T >::operator-= (const ContainedType & val)
References Safir::Dob::Typesystem::ContainerProxy< T >::GetVal(), and Safir::Dob::Typesystem::ContainerProxy< T >::SetVal().
operator/=()
template<class T> ContainerProxy& Safir::Dob::Typesystem::ContainerProxy< T >::operator/= (const ContainedType & val)
References Safir::Dob::Typesystem::ContainerProxy< T >::GetVal(), and Safir::Dob::Typesystem::ContainerProxy< T >::SetVal().
operator=() [1/2]
template<class T> ContainerProxy& Safir::Dob::Typesystem::ContainerProxy< T >::operator= (const ContainerProxy< T > & other)
References Safir::Dob::Typesystem::ContainerProxy< T >::GetVal(), and Safir::Dob::Typesystem::ContainerProxy< T >::IsNull().
operator=() [2/2]
template<class T> ContainerProxy& Safir::Dob::Typesystem::ContainerProxy< T >::operator= (const ContainedType other)
SetChanged()
template<class T> void Safir::Dob::Typesystem::ContainerProxy< T >::SetChanged (const bool changed)
SetNull()
template<class T> void Safir::Dob::Typesystem::ContainerProxy< T >::SetNull ()
Referenced by Safir::Dob::Typesystem::ContainerProxy< StringContainer >::operator=(), Safir::Dob::Typesystem::ContainerProxy< BinaryContainer >::operator=(), Safir::Dob::Typesystem::ContainerProxy< ObjectContainerImpl< U > >::operator=(), and Safir::Dob::Typesystem::ContainerProxy< ObjectContainerImpl< Object > >::operator=().
SetOrdinal()
template<class T> void Safir::Dob::Typesystem::ContainerProxy< T >::SetOrdinal (const EnumerationValue value)
SetVal()
template<class T> void Safir::Dob::Typesystem::ContainerProxy< T >::SetVal (const ContainedType value)
Referenced by Safir::Dob::Typesystem::ContainerProxy< T >::operator*=(), Safir::Dob::Typesystem::ContainerProxy< T >::operator++(), Safir::Dob::Typesystem::ContainerProxy< T >::operator+=(), Safir::Dob::Typesystem::ContainerProxy< StringContainer >::operator+=(), Safir::Dob::Typesystem::ContainerProxy< T >::operator--(), Safir::Dob::Typesystem::ContainerProxy< T >::operator-=(), Safir::Dob::Typesystem::ContainerProxy< T >::operator/=(), Safir::Dob::Typesystem::ContainerProxy< StringContainer >::operator=(), and Safir::Dob::Typesystem::ContainerProxy< BinaryContainer >::operator=().